### ISSUE TITLE
As a user I want to have a visual interface so that I more easily can generate recipes and interact with the api

### ISSUE THREAD

**Issue by chrille0313** [chrille0313/DishPlanner#10]
## TODO

- [x] #16
- [x] #17

### UI Components
- [x] Create "recipe column" component

### Logic
- [x] Query backend api
- [x] Link api result to ui component

### React
- Getting started with a react application (Read "Getting Started" and "Folder Structure"): 
   https://create-react-app.dev/docs/getting-started

- Importing and exporting components:
   https://create-react-app.dev/docs/importing-a-component

- Styling components (CSS):
   https://create-react-app.dev/docs/adding-a-css-modules-stylesheet

- Linking frontend to backend:
   https://www.tutorialspoint.com/how-to-connect-reactjs-with-flask-api
