### ISSUE TITLE
As a user I want to be able to filter recipes on the frontend so that I can get relevant recipes in accordance to my food preferences

### ISSUE THREAD

**Issue by chrille0313** [chrille0313/DishPlanner#24]
# Todo
- [x] Create dropdown button component
- [x] Add filtering options in dropdown component instance
- [x] Extract filter params from component instance
- [x] Query backend with filters
