### ISSUE TITLE
As a user I want to be able to FILTER the recipes so that I can adapt to my food preferences

### ISSUE THREAD

**Issue by chrille0313** [chrille0313/DishPlanner#8]
## TODO
- [x] Find relevant query parameters
- [x] Add ability to read query params on api endpoint from controller
- [x] Query recipe api based on params
- [x] #13

**Comment by chrille0313** [comment]
Let's finish all tasks before closing this as done.
